on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

name: test-coverage

jobs:
  test-coverage:
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config
          brew install gdal

      - uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: 'https://predictiveecology.r-universe.dev/'
          Ncpus: 2
          use-public-rspm: false

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
